title: Dudley-Dixon Family History
description:

collections_dir: items
collections:
  events:
    output: true
  people:
    output: true
  places:
    output: true
  sources:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "events"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "people"
    values:
      layout: "person"
  -
    scope:
      path: ""
      type: "places"
    values:
      layout: "place"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /about/:year/:title:output_ext
  -
    scope:
      path: ""
      type: "sources"
    values:
      layout: "default"
