baseurl: /family-history

collections_dir: _collections
collections:
  people:
    output: true
  places:
    output: true

defaults:
  - scope:
      path: ""
      type: "people"
    values:
      layout: "person"
  - scope:
      path: ""
      type: "places"
    values:
      layout: "default"
